[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
anyhow = "1.0.68"
itertools = "0.10.5"
lazy_static = "1.4.0"
nom = "7.1.1"
regex = "1.7.0"
thiserror = "1.0.38"
